services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "21433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Your_password123 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
  webapi:
    build: ./DemoApp
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Server=sqlserver;Database=DemoAppDb;User=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - sqlserver
    ports:
      - "5000:8080"
    command: ["dotnet", "DemoApp.dll"]
